# It's used for complication in Mac Host, not including iOS compliation.

parameters:
- name: TODAY
  type: string

- name: BuildStep
  type: stepList

- name: AdditionalKey
  type: string

steps:
  - script: |
      brew install ccache
      echo "##vso[task.prependpath]/usr/local/opt/ccache/libexec"
      mkdir -p "$(Pipeline.Workspace)/ccache"
      ls "$(Pipeline.Workspace)"
    displayName: Install ccache and update PATH to use linked versions of gcc, cc, etc

  - task: Cache@2
    inputs:
      key:  ' "${{parameters.TODAY}}" | ${{parameters.AdditionalKey}} | "$(Build.SourceVersion)" '
      path: $(CCACHE_DIR)
      restoreKeys: |
        "${{parameters.TODAY}}" | ${{parameters.AdditionalKey}}
    displayName: ccache task
    env:
      CCACHE_DIR: '$(Pipeline.Workspace)/ccache'

  - ${{ parameters.BuildStep }}

  - script: |
      ccache -s
      ccache -z
    displayName: Show Cache stats and Clear stats.
