jobs:
- job: CoreML_CI
  pool:
    vmImage: 'macOS-12'
  variables:
    MACOSX_DEPLOYMENT_TARGET: '10.14'
  timeoutInMinutes: 120
  steps:
  - script: brew install coreutils ninja
    displayName: Install coreutils and ninja

  - script: |
      brew install ccache
      echo "##vso[task.prependpath]/usr/local/opt/ccache/libexec"
    displayName: Install ccache and update PATH to use linked versions of gcc, cc, etc

  - task: Cache@2
    inputs:
      key:  ' "$(TODAY)" | coreml | "$(Build.SourceVersion)" '
      path: $(CCACHE_DIR)
      restoreKeys: |
        "$(TODAY)" | coreml
    displayName: ccache task

  - script: |
      python3 tools/ci_build/build.py \
      --build_dir build \
      --skip_submodule_sync \
      --cmake_generator=Ninja \
      --parallel \
      --build_shared_lib \
      --config Debug \
      --use_coreml
    displayName: CoreML EP, Build and Test on macOS

  - script: |
      ccache -s
      ccache -z
    displayName: Show Cache stats and Clear stats.
