jobs:
- job: CoreML_CI
  pool:
    vmImage: 'macOS-12'
  variables:
    MACOSX_DEPLOYMENT_TARGET: '10.14'
    TODAY: $[format('{0:dd}{0:MM}{0:yyyy}', pipeline.startTime)]
  timeoutInMinutes: 120
  steps:
  - script: brew install coreutils ninja
    displayName: Install coreutils and ninja

  - template: templates/mac-build-step-with-cache.yml
    parameters:
      TODAY: $(TODAY)
      AdditionalKey: coreml
      BuildStep:
        - script: |
            python3 tools/ci_build/build.py \
            --build_dir build \
            --skip_submodule_sync \
            --parallel \
            --build_shared_lib \
            --config Debug \
            --use_coreml
          displayName: CoreML EP, Build and Test on macOS
